### ISSUE TITLE
DGND and AGND

### ISSUE THREAD

**Issue by ethanharstad** [ethanharstad/STM32-CSK-Module#4]
Are these connected anywhere in the existing system? Do they need to be connected on the PPM?

**Comment by imciner2** [comment]
The ClydeSpace powerboard does not show AGND (H2.31) going into the board.
The Astrodev radio does not use AGND either.
However, the Gomspace shows AGND being available on their power board.

To allow for better compatibility in the CubeSat family, it is probably safer to not connect AGND to DGND directly on on the module and instead use a solder jumper or zero-ohm resistor. That would avoid the having a ground loop formed on the module accidentally.

**Comment by ethanharstad** [comment]
I will use a 0 ohm for now
